import os
from dotenv import load_dotenv

load_dotenv()

HOST = os.getenv("HOST", "127.0.0.1")
PORT = int(os.getenv("PORT", "8002"))
TASK_PREFIX_API = os.getenv("TASK_PREFIX_API")
THEME_PREFIX_API = os.getenv("THEME_PREFIX_API")

DATABASE_URL = os.getenv("DATABASE_URL")

AUTH_SERVICE_HOST = os.getenv("AUTH_SERVICE_HOST")
AUTH_SERVICE_PORT = os.getenv("AUTH_SERVICE_PORT")
AUTH_SERVICE_AUTH_PREFIX_API = os.getenv("AUTH_SERVICE_AUTH_PREFIX_API")
AUTH_SERVICE_POSSIBILITY_PREFIX_URL = os.getenv("AUTH_SERVICE_POSSIBILITY_PREFIX_API")

SOLUTION_SERVICE_HOST=os.getenv("SOLUTION_SERVICE_HOST")
SOLUTION_SERVICE_PORT=os.getenv("SOLUTION_SERVICE_PORT")
SOLUTION_SERVICE_SOLUTION_PREFIX_API=os.getenv("SOLUTION_SERVICE_SOLUTION_PREFIX_API")