import os

from fastapi.security import OAuth2PasswordBearer

AUTH_SERVICE_HOST = os.getenv("AUTH_SERVICE_HOST")
AUTH_SERVICE_PORT = os.getenv("AUTH_SERVICE_PORT")
AUTH_SERVICE_AUTH_PREFIX_API = os.getenv("AUTH_SERVICE_AUTH_PREFIX_API")
AUTH_SERVICE_POSSIBILITY_PREFIX_URL = os.getenv("AUTH_SERVICE_POSSIBILITY_PREFIX_API")

ANSWER_SUBMISSION_MANAGEMENT_SERVICE_HOST=os.getenv("ANSWER_SUBMISSION_MANAGEMENT_SERVICE_HOST")
ANSWER_SUBMISSION_MANAGEMENT_SERVICE_PORT=os.getenv("ANSWER_SUBMISSION_MANAGEMENT_SERVICE_PORT")
ANSWER_SUBMISSION_MANAGEMENT_SERVICE_ANSWER_PREFIX_API=os.getenv("ANSWER_SUBMISSION_MANAGEMENT_SERVICE_ANSWER_PREFIX_API")

oauth2_scheme = OAuth2PasswordBearer(
    tokenUrl=f"http://{AUTH_SERVICE_HOST}:{AUTH_SERVICE_PORT}/{AUTH_SERVICE_AUTH_PREFIX_API}/login",
)